namespace D.D.Entities.Enum
{
    public enum Atributos : int
    {
        Abencoado = 1,
        Agua = 2,
        Anjo = 3,
        Artificial = 4,
        Assassino = 5,
        Automata = 6,
        Bandido = 7,
        Bruxaria = 8,
        Coletivo = 9,
        Conhecimento = 10,
        Corrompido = 11,
        Cosmico = 12,
        Criatura_da_Noite = 13,
        Demonio = 14,
        Descontrolado = 15,
        Deus = 16,
        Divino = 17,
        Energia_Espiritual = 18,
        Escuridao = 19,
        Espaco_Tempo = 20,
        Espirito = 21,
        Faminto = 22,
        Feiticeiro = 23,
        Fera = 24,
        Florestal = 25,
        Fogo = 26,
        Gelo = 27,
        Guardiao = 28,
        Guerreiro = 29,
        Heroi = 30,
        Ilusao = 31,
        Luar = 32,
        Luz = 33,
        Mago = 34,
        Maldicao = 35,
        Mestre_da_Luta = 36,
        Mestre_de_Armas = 37,
        Mestre_Sabio = 38,
        Metamorfo = 39,
        Monstro = 40,
        Nucle_de_Energia = 41,
        Parasita = 42,
        Pesadelo = 43,
        Raio = 44,
        Sangue = 45,
        Sensorial = 46,
        Sobrenatural = 47,
        Sun = 48,
        Telepatia = 49,
        Terra = 50,
        Terror_Bioquimico = 51,
        Toxico = 52,
        Undead = 53,
        Vilao = 54,

    }
}
